#automatisera containers i pipeline
# måste ha github container registry för att pulla image



name: Build and Push Redis Containers to Ghcr

#trigger when workflow build-and-push-backend-container is completed
on:
  workflow_run:
    workflows: ["Build and Push Postgres Container to Ghcr(Github Container Registry)"]  # Namnet på workflow som måste vara klar först
    types:
      - completed

#bygga redis image
jobs:
  
  build-redis-container-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
   #Kollar repot
      - name: Checkout repo
        uses: actions/checkout@v4

    # Logga in på Github för att pusha och pulla images i Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN2026 }}
    
    #Bygger redis image med container
      - name: Build and push redis image to Container Registry
        run: |
          docker build -f redis/Containerfile -t ghcr.io/almafrank/redis-guestbook:latest redis
          docker push ghcr.io/almafrank/redis-guestbook:latest
      

      

  





