name: Build container image Frontend and Push Containers to GHCR
#trigger feature branch
on:
  workflow_call:
     secrets:
      TOKEN2026:
        required: true
#bygga postgres image
jobs:
  build-and-push-frontend-container-image:
   
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write


    

    steps:
   #Kollar repot
      - name: Checkout repo
        uses: actions/checkout@v4
    
      - name: Generate image tag
        id: image-tag
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          IMAGE_TAG="1.0.${GITHUB_RUN_NUMBER}-${SHORT_SHA}"
          echo "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "Generated tag: ${IMAGE_TAG}"

    # Logga in på Github för att pusha och pulla images i Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN2026 }}
    
    #Bygger frontend image med container
      - name: Build and push frontend image to Container Registry
        run: |
          docker build -f frontend/Containerfile \
          -t ghcr.io/almafrank/frontend-guestbook:${{ steps.image-tag.outputs.tag }} \
          -t ghcr.io/almafrank/frontend-guestbook:latest \
          frontend

          docker push ghcr.io/almafrank/frontend-guestbook:${{ steps.image-tag.outputs.tag }}
          docker push ghcr.io/almafrank/frontend-guestbook:latest
  
  