name: Build container image Backend 
#trigger feature branch
on:
  workflow_call:
     secrets:
      TOKEN2026:
        required: true
      KUBERNETESSANDBOXTOKEN:
        required: true

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: almafrank/backend-guestbook
  CONFIG_REPO: almafrank/KubernetesSandbox
  
jobs:
  build-and-push-backend-container-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    

    
    steps:
      #Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # Login pÃ¥ Github 
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{env.IMAGE_REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN2026}}

       # Generate image tag
      - name: Generate image tag
        id: image-tag
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          IMAGE_TAG="1.0.${GITHUB_RUN_NUMBER}-${SHORT_SHA}"
          echo "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "Generated tag: ${IMAGE_TAG}"
      
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Containerfile
          push: true
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            APP_VERSION=${{ steps.image-tag.outputs.tag }}
      

    
     
      
      - name: Show generated tag
        run: echo "TAG=${{ steps.image-tag.outputs.tag }}"
      
      - name: Checkout Kubernetes Sandbox repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.CONFIG_REPO }}
          token: ${{ secrets.KUBERNETESSANDBOXTOKEN }}
          path: sandbox
     
      
      - name: Update Kubernetes manifests
        run: |
          
          sed -i "s|image: .*backend-guestbook.*|image: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}|" sandbox/backend.yaml

          git config user.name "almafrank"
          git config user.email "almafrank107@yahoo.com"
          git add sandbox/backend.yaml
          git commit -m "Update backend image to ${{ steps.image-tag.outputs.tag }}"
          git push origin main
      
      
      
     
     
      
      