name: Build container image Backend and Push Containers to GHCR
#trigger feature branch
on:
  workflow_call:
     secrets:
      TOKEN2026:
        required: true
      KUBERNETESSANDBOXTOKEN:
        required: true
#bygga postgres image
jobs:
  build-and-push-backend-container-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    outputs:
      tag: ${{ steps.image-tag.outputs.tag }}


    
    steps:
   #Kollar repot
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Generate image tag
        id: image-tag
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          IMAGE_TAG="1.0.${GITHUB_RUN_NUMBER}-${SHORT_SHA}"
          echo "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "Generated tag: ${IMAGE_TAG}"

    # Logga in på Github för att pusha och pulla images i Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN2026}}
    
    #Bygger backend image med container
      - name: Build and push backend image to Container Registry
        run: |
          docker build -f backend/Containerfile \
            -t ghcr.io/almafrank/backend-guestbook:${{ steps.image-tag.outputs.tag }} \
            ./backend

          docker push ghcr.io/almafrank/backend-guestbook:${{ steps.image-tag.outputs.tag }}
      
      - name: Show generated tag
        run: echo "TAG=${{ steps.image-tag.outputs.tag }}"
      
      
      - name: Checkout Kubernetes Sandbox repo
        uses: actions/checkout@v4
        with:
          repository: almafrank/KubernetesSandbox
          token: ${{ secrets.KUBERNETESSANDBOXTOKEN }}
          path: KubernetesSandbox
     
     
      - name: Update backend image in Kubernetes Sandbox
        run: |
          sed -i "s|image: ghcr.io/almafrank/backend-guestbook:.*|image: ghcr.io/almafrank/backend-guestbook:${{ steps.image-tag.outputs.tag }}|" KubernetesSandbox/sandbox/backend.yaml
      
      - name: Commit and push changes
        run: |
          git config user.name "almafrank"
          git config user.email "almafrank107@yahoo.com"
          git add KubernetesSandbox/sandbox/backend.yaml
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update backend image to: ${{ steps.image-tag.outputs.tag }}"
            git push origin main
          fi
          