name: Build container image Frontend 
#trigger feature branch
on:
  workflow_call:
     secrets:
      TOKEN2026:
        required: true
      KUBERNETESSANDBOXTOKEN:
        required: true

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: almafrank/frontend-guestbook
  CONFIG_REPO: almafrank/KubernetesSandbox

jobs:
  build-and-push-frontend-container-image:
   
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    


    

    steps:
   
      - name: Checkout repo
        uses: actions/checkout@v4
      
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{env.IMAGE_REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN2026 }}
    
      - name: Generate image tag
        id: image-tag
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          IMAGE_TAG="1.0.${GITHUB_RUN_NUMBER}-${SHORT_SHA}"
          echo "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "Generated tag: ${IMAGE_TAG}"

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Containerfile
          push: true
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            APP_VERSION=${{ steps.image-tag.outputs.tag }}

    
    
      - name: Show generated tag
        run: echo "TAG=${{ steps.image-tag.outputs.tag }}"

      - name: Update Kubernetes manifests
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git clone https://${{ secrets.KUBERNETESSANDBOXTOKEN }}@github.com/${{ env.CONFIG_REPO }}.git sandbox
          cd sandbox

          sed -i "s|image: .*frontend-guestbook:.*|image: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}|" sandbox/frontend.yaml
          sed -i "s|value: \".*\"|value: \"${{ steps.image-tag.outputs.tag }}\"|" sandbox/frontend.yaml

          git add sandbox/frontend.yaml
          git commit -m "Update image to ${{ steps.image-tag.outputs.tag }}"
          git push origin main
      
      
     
     
      
      
      
       

      
      
     