#automatisera containers i pipeline
# måste ha github container registry för att pulla image



name: Build and Push Containers to Ghcr

#trigger feature branch
on:
  push:
    branches: 
      - feature/* 
      
  pull_request:
    branches:
      - main  

#bygga frontend image
jobs:
  
  build-frontend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
   #Kollar repot
      - name: Checkout repo
        uses: actions/checkout@v4

    # Logga in på Github för att pusha och pulla images i Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN2026 }}
    
    #Bygger frontend image med container
      - name: Build and push frontend image to Container Registry
        run: |
          docker build -f frontend/Containerfile -t ghcr.io/almafrank/frontend-guestbook:latest frontend
          docker push ghcr.io/almafrank/frontend-guestbook:latest
      

      

  build-backend:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:

    #Kollar repot
      - name: Checkout repo
        uses: actions/checkout@v4

    # Logga in på Github för att pusha och pulla images i Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN2026 }}
    
    #Bygger backend image med container
      - name: Build and push backend image to Container Registry
        run: |
          docker build -f backend/Containerfile -t ghcr.io/almafrank/backend-guestbook:latest backend
          docker push ghcr.io/almafrank/backend-guestbook:latest
    
  build-postgres:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:

    #Kollar repot
      - name: Checkout repo
        uses: actions/checkout@v4

    # Logga in på Github för att pusha och pulla images i Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN2026 }}
    
    #Bygger backend image med container
      - name: Build and push postgres image to Container Registry
        run: |
          docker build -f postgres/Containerfile -t ghcr.io/almafrank/postgres-guestbook:latest postgres
          docker push ghcr.io/almafrank/postgres-guestbook:latest
  
  build-redis:
    needs: build-postgres
    runs-on: ubuntu-latest
    steps:

    #Kollar repot
      - name: Checkout repo
        uses: actions/checkout@v4

    # Logga in på Github för att pusha och pulla images i Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN2026 }}
    
    #Bygger backend image med container
      - name: Build and push redis image to Container Registry
        run: |
          docker build -f redis/Containerfile -t ghcr.io/almafrank/redis-guestbook:latest redis
          docker push ghcr.io/almafrank/redis-guestbook:latest

      
          
          
      
     


  

    
    



    











