name: Build and Push Postgres Container to Ghcr(Github Container Registry)
#trigger feature branch
on:
  push:
    branches: 
      - feature/* 
      
  pull_request:
    branches:
      - main  

#bygga postgres image
jobs:
  
  build-postgres-container-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
   #Kollar repot
      - name: Checkout repo
        uses: actions/checkout@v4

    # Logga in på Github för att pusha och pulla images i Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN2026 }}
    
    #Bygger postgres-db image med container
      - name: Build and push postgres image to Container Registry
        run: |
          docker build -f postgres/Containerfile -t ghcr.io/almafrank/postgres-guestbook:latest postgres
          docker push ghcr.io/almafrank/postgres-guestbook:latest