name: Build and Push Backend Container to Ghcr(Github Container Registry)

#trigger when workflow build-and-push-backend-container is completed
on:
  workflow_run:
    workflows: ["Build and Push Redis Containers to Ghcr"]  # Namnet på workflow som måste vara klar först
    types:
      - completed


#bygga backend image
jobs:
  
  build-backend-container-image:
    
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
   #Kollar repot
      - name: Checkout repo
        uses: actions/checkout@v4

    # Logga in på Github för att pusha och pulla images i Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN2026 }}
    
    #Bygger backend image med container
      - name: Build and push backend image to Container Registry
        run: |
          docker build -f backend/Containerfile -t ghcr.io/almafrank/backend-guestbook:latest backend
          docker push ghcr.io/almafrank/backend-guestbook:latest
      
    